### ISSUE TITLE
Non-ECMA behavior of `(.*?)*` and similar constructs

### ISSUE THREAD

**Issue by Grimy** [Davidebyzero/RegexMathEngine#1]
One of the differences between ECMA and PCRE is the treatment of quantifiers on sub-patterns that can match the empty string. RegexMathEngine currently doesn't support the ECMA behavior, and instead matches the PCRE behavior even when `--pcre` isn't given.

See [the ECMA specification of quantifiers](https://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-repeatmatcher-abstract-operation), in particular Note 4:

> once the minimum number of repetitions has been satisfied, any more expansions of Atom that match the empty character sequence are not considered for further repetitions

This implies that `(.*?)*` should be equivalent to `(.+?)*` and match everything. Slightly trickier examples: `(.*?)?` and `(.*?){7,8}` should both match a single character.

### Tests

RegexMathEngine:

    echo xxx | regex -o '^.(.*?)*'
    x

Firefox:

    "xxx".match(/^.(.*?)*/)[0]
    "xxx"

Perl:

     perl -le '"xxx" =~ /^.(.*?)*/; print $&'
     x

PCRE:

    echo xxx | grep -Po '^.(.*?)*'
    x

**Comment by Davidebyzero** [comment]
Thank you very much! [Now fixed.](https://github.com/Davidebyzero/RegexMathEngine/commit/7047d9edd5e3362f01019a132722906c392ce9d9) Do I need to change the behavior of lazy groups too or was it already correct?

**Comment by Grimy** [comment]
Confirmed fixed. I did somes tests with lazy groups and I don’t think there’s an observable difference between PCRE and ECMA here.

**Comment by Grimy** [comment]
Digging some more, I found an (extremely minor) difference with lazy groups. `()??\1` matches the empty string in both PCRE and ECMA, but in PCRE it sets \1 to the empty string, whereas in ECMA it leaves \1 undefined. Since there's no way to differentiate between an NPCG and an empty capture group from within an ECMA pattern, this doesn't usually matter.

However, it does matter in some of the hybrid dialects suported by RegexMathEngine. For example, `regex --neam+ --npcg- '()??\1'` shouldn't match anything (but currently does). Of course, that's more a curiosity than a real issue.

(By the way, my 66-char solution to [your log2 golf challenge](https://gist.github.com/Davidebyzero/9735222#gistcomment-1210297) only works with `--neam-`, but thanks to this fix I managed to find a 70-char that works either way.)

**Comment by Davidebyzero** [comment]
I was thinking of `echo 'az' | ./regex -xpbr -o '^(?:(?=(\1a)))??\1z'`, which should not match in `--neam+` mode, but I like your example too! And I definitely want these to behave as they logically should in the hybrid modes. (I also need to allow quantifiers to work on assertions as they do in PCRE2 and the latest PCRE. And I just realized that the fact that `^(?=(.))?\1` is an empty match in Firefox and Chrome is completely consistent with ECMAScript's `--neam+` behavior, and not a special case that only applies to assertions, as I have it currently implemented. So all I need to do is make them work in the PCRE way in `--neam-` mode.)

Incidentally, this is another thing that .NET's ECMAScript emulation mode [gets wrong](https://tio.run/##K0otycxLNPwfk6LNpVXBpa2aEKdRoaWpG2NYoc2lYnhoW4WKAZdqqkaCboUW1/84DT0te81qYx3T2v/qKgbqXCABTXU4AdShYqRirPCobZKCihFXXIWWhr2tQo2KZo2GvY2tgmaFlgqXip7BfwNdQwMA "Retina – Try It Online"). The other thing is that while it does emulate `--npcg+` and disable forward backreferences, it [doesn't disable nested backreferences](https://tio.run/##K0otycxLNPwfk6LNpVXBpa2aEKdRoaWpG2NYoc2lYnhoW4WKAZdqqkaCboUW1/@4Cg0grIgx0tTUUvmvomfLpZkAVMflnhCT8t9A18TAAAA).
