### ISSUE TITLE
Incorrect handling of [-...] and [...-]

### ISSUE THREAD

**Issue by Grimy** [Davidebyzero/RegexMathEngine#2]
### Current behavior

* `[-]` matches nothing
* `[^-]` matches any character
* `[+-]` only matches `+`
* `[-+]` **hangs**

### Expected behavior

* `[-]` matches `-`
* `[^-]` matches any character except `-`
* `[+-]` matches `+` or `-`
* `[-+]` matches `+` or `-`

This is the behavior in all of ECMA, PCRE, and Perl.

**Comment by Davidebyzero** [comment]
Strange, I meant it to work that way, but it seems I must not have tested it. Anyway, fixed now.
